baseURL = "https://cmluciano.github.io/"
languageCode = "en-us"
author = "Christopher M Luciano"
title = "A real blog's blog"
theme = "blackburn"
Paginate = 10
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "cmluciano_"

  # SNS career oriented
  linkedin = "cmluciano"
   
  # Techie
  github = "cmluciano"
  stackoverflow = "cluciano"

  # Gaming
  steam = "racerxpa7777"
  ps4 = "ITmedic62"